name: Run Tests
# Run in all PRs and commits to `master` and releases
on:
  pull_request:
  push:
    branches:
      - master
      - release-*
      - issue-*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}      

      - name: Setting Node.js 10.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: '10.15.3'  
      
      - name: Installing dependencies
        run: npm install

      - name: Building libraries
        run: npm run build:libs

      - name: Building production
        run: npm run build:prod

      - name: Running tests
        run: |
          npm run test-headless
       
      - name: Setting up Google Cloud    
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
          export_default_credentials: true
      - run: gcloud info
          