name: Run Tests
# Run in all PRs and commits to `master` and releases
on:
  pull_request:
  push:
    branches:
      - master
      - release-*
      - issue-*
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./dotcicd/test-results
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}      

      - name: Setting Node.js 10.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: '10.15.3'
      
      - name: Installing dependencies
        run: npm install

      - name: Building libraries
        run: npm run build:libs

      - name: Building production
        run: npm run build:prod

      - name: Running tests
        run: |
          npm run test-headless
      
      - name: Prepare dot-cicd
        run: |
          chmod +x .cicd/github.sh && source .cicd/github.sh
          checkForToken ${GITHUB_TOKEN}

      - name: Check files
        run: |
          cd ./dotcicd/test-results/projects/core-web/${GITHUB_SHA::8}
          ls
      - name: Setup user
        run: |
          git config --local user.email "ivorjpc@gmail.com"
          git config --local user.name "ivorpad"
          git config --local --unset-all http.https://github.com/.extraheader
          git config -l | grep user
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ivorpad/test-results