name: Run Tests
# Run in all PRs and commits to `master` and releases
on:
  pull_request:
  push:
    branches:
      - master
      - release-*
      - issue-*
jobs:
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}      

      - name: Setting Node.js 10.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: '10.15.3'
      
      - name: Prepare test repo
        run: |
          chmod +x .cicd/github.sh && source cicd/github.sh
          checkForToken ${GITHUB_TOKEN}


      # - name: Installing dependencies
      #   run: npm install

      # - name: Building libraries
      #   run: npm run build:libs

      # - name: Building production
      #   run: npm run build:prod

      # - name: Running tests
      #   run: |
      #     npm run test-headless
      
    
      # fetch the test-results repo
      # commit 
