name: DotCMS/core-web Tests
on:
  pull_request:
  push:
    branches:
      - master
      - release-*
      - issue-*
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_USER_TOKEN }}
      GITHACK: "raw.githack.com"
      TEST_RESULTS: "test-results"
      GITHUB_TEST_RESULTS_PATH: "DotCMS/${TEST_RESULTS}"
      GITHACK_TEST_RESULTS_URL: "https://${GITHACK}/${GITHUB_TEST_RESULTS_PATH}"
      DOT_CICD_TARGET: "core-web"
      GITHUB_TEST_RESULTS_BROWSE_URL: "${GITHACK_TEST_RESULTS_URL}/${GITHUB_SHA::8}/projects/${DOT_CICD_TARGET}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./dotcicd/test-results
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}      
      - name: Setting Node.js 10.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: '10.15.3'
      - name: Installing dependencies
        run: npm install
      - name: Building Libs
        run: npm run build:libs
      - name: Building for production
        run: npm run build:prod
      - name: Running tests
        run: |
          npm run test-headless    
      - name: Prepare and Push to GitHub
        run: |
          chmod +x .cicd/github.sh && source .cicd/github.sh
      - name: Printing Logs
        run: |
          echo ${GITHUB_TEST_RESULTS_BROWSE_URL}/report.html