name: Run Tests
# Run in all PRs and commits to `master` and releases
on:
  pull_request:
  push:
    branches:
      - master
      - release-*
      - issue-*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.15.3'  
      - name: Test node version
        run: node --version    
      - name: Install dependencies
        run: npm install
      - name: Building libraries
        run: npm run build:libs
      - name: Building production
        run: npm run build:prod
      - name: Running tests
        run: |
          npm run test-headless
      - uses: actions/upload-artifact@v2   
        with:
          name: report
          path: karma_html/ # or path/to/artifact
