name: Run Tests
# Run in all PRs and commits to `master` and releases
on:
  pull_request:
  push:
    branches:
      - master
      - release-*
      - issue-*
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cd
        run: |
          pwd
          ls
          mkdir hello
          cd hello
          touch index.html
          mkdir against
          cd ~
          cd work
          ls
          pwd
