name: Publish to Dotcms Webcomponents
on:
  push:
      branches:
          - issue-20245-automate-dotwebcomponents-generation
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
              fetch-depth: 1
        - name: Configuring Node.js
          uses: actions/setup-node@v2-beta
          with:
              node-version: '10.15.3'
        - name: Installing dependencies
          run: npm install
        - name: "Automated Version Bump"
          id: version-bump
          uses: "phips28/gh-action-bump-version@master"
          with:
            commit-message: 'CI: bumps version to {{version}} [skip ci]'
            skip-tag:  'true'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PACKAGEJSON_DIR:  'libs/dotcms-webcomponents'
        - name: Build dotcms-webcomponents with deps
          run: |
            npm run nx build dotcms-ui -- --with-deps --prod
        - name: "publish to npm"
          run: |
              cd dist/libs/dotcms-webcomponents
              npm publish

