name: Publish to Dotcms Webcomponents
on:
  push:
      branches:
          # - issue-20245-automate-dotwebcomponents-generation
          - release-*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout core-web
          uses: actions/checkout@v2
          with:
              fetch-depth: 1
              path: 'core-web'
        - name: Configuring Node.js
          uses: actions/setup-node@v2-beta
          with:
              node-version: '10.15.3'
        - name: Installing dependencies
          run: npm install
        - name: "Automated Version Bump - dotcms-webcomponents"
          id: version-bump
          uses: "phips28/gh-action-bump-version@master"
          with:
            commit-message: 'CI: bumps version to {{version}} [skip ci]'
            skip-tag:  'true'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PACKAGEJSON_DIR:  'core-web/libs/dotcms-webcomponents'
        # - name: Build dotcms-webcomponents with deps
        #   run: |
        #     cd core-web
        #     npm run nx build dotcms-ui -- --with-deps --prod
        # - name: "publish to npm"
        #   run: |
        #       cd core-web
        #       npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        #       cd core-web/dist/libs/dotcms-webcomponents
        #       npm publish
        - name: Set Core SSH keys
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            echo "${{ secrets.CORE_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
        - name: Checkout Core & Bump webComponentsReleaseVersion, only on a release branch
          env:
            GITHUB_USER: dotcmsbuild
          run: |
            if [[ $(basename "${{ github.ref }}") =~ ^release-.* ]]
            then
              CURRENT_BRANCH=$(basename "${{ github.ref }}")
              git config --global user.email "${GITHUB_USER}@dotcms.com"
              git config --global user.name "${GITHUB_USER}"
              git clone git@github.com:dotCMS/core.git ../core
              cd ../core
              git checkout -b ${CURRENT_BRANCH} --track origin/${CURRENT_BRANCH}
              cd dotCMS
              NEW_VERSION="${{ steps.version-bump.outputs.newTag }}"
              sed -i "s|webComponentsReleaseVersion=.*|webComponentsReleaseVersion=${NEW_VERSION:1}|g" gradle.properties
              git add .
              echo "*** 8"
              git commit -m "CI: bumps webComponentsReleaseVersion to ${NEW_VERSION:1} [skip ci]"
              git push origin ${CURRENT_BRANCH}
            else
              echo "Skipping bump, not a release brach"
            fi
